/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-08-26 04:54:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.tech.blog.helper.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/normal_navbar.jsp", Long.valueOf(1692908743414L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.tech.blog.helper");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- this is css bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\" />\r\n");
      out.write(" <!-- this is font icon awensome --> \r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("   <link href=\"css/NewFile.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write(" \r\n");
      out.write(" <!-- from here we are using the clip path for that following link -->\r\n");
      out.write("   <style>\r\n");
      out.write("   .banner-background{\r\n");
      out.write("   \r\n");
      out.write("   clip-path: polygon(50% 0%, 100% 0, 100% 35%, 100% 92%, 80% 88%, 49% 96%, 20% 92%, 0 93%, 0% 35%, 0 0);\r\n");
      out.write("   }\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("   </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- this is for navbar -->\r\n");
      out.write("       ");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark userdefinecolor-background\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"index.jsp\"> <span class=\"fa fa-bullseye\"></span> techBlog</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\"> <span class=\"	fa fa-check-square\"></span> learnCode with Ritik <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("          Categories\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Programming Language</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Project Implementation</a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Data Structure</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"Login_jsp.jsp\"> <span class=\"fa fa-user-circle\"></span> Login</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"register_page.jsp\"> <span class=\"fa fa-user-plus\"></span>Sign up</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- this is for //banner -->\r\n");
      out.write("\r\n");
      out.write("     <div class=\"container-fluid p-0 m-0\">\r\n");
      out.write("     \r\n");
      out.write("     <div class=\"jumbotron userdefinecolor-background  banner-background text-white\">\r\n");
      out.write("     <div class=\"container\">\r\n");
      out.write("     <h3 class=\"display-3\">welcome Tech Blog</h3>\r\n");
      out.write("     <h3></h3>\r\n");
      out.write("     <p>\r\n");
      out.write("     \r\n");
      out.write("     A programming language is a system of notation for writing computer programs.\r\n");
      out.write("     [1] Most programming languages are text-based formal languages, but they may also be graphical. \r\n");
      out.write("     They are a kind of computer language.\r\n");
      out.write("     \r\n");
      out.write("     </p>\r\n");
      out.write("     <p>\r\n");
      out.write("     The description of a programming language is usually split into the two components of syntax (form) and semantics (meaning),\r\n");
      out.write("      which are usually defined by a formal language. Some languages are defined by a specification \r\n");
      out.write("      document (for example, the C programming language is specified by an ISO Standard) \r\n");
      out.write("      while other languages (such as Perl) have a dominant implementation that is treated as a \r\n");
      out.write("      reference. S\r\n");
      out.write("     \r\n");
      out.write("     </p>\r\n");
      out.write("     <button class=\"btn btn-outline-light btn-lg\"> <span class=\"fa fa-external-link\"></span> start! itts Free</button>\r\n");
      out.write("     <a href=\"Login_jsp.jsp\" class=\"btn btn-outline-light btn-lg\"> <span class=\"fa fa-user-circle-o fa-spin\"></span> login</a>\r\n");
      out.write("     </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div> \r\n");
      out.write("     \r\n");
      out.write("     <!--  this is card -->\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("     <div class=\"row mb-4\">\r\n");
      out.write("     <!-- this is first column -->\r\n");
      out.write("      <div class=\"col-md-4 col-lg-4 col-xl-4\">     \r\n");
      out.write("       <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"...\" alt=\"Card image cap\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">JAVA PROGRAMMING LANGUAGE</h5>\r\n");
      out.write("          <p class=\"card-text\">Some quick example text to build on the card title and make up the bulk of the card's content.</p>\r\n");
      out.write("           <a href=\"#\" class=\"btn userdefinecolor-background text-white\">Read More..</a>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <!-- this is second column -->\r\n");
      out.write("      <div class=\"col-md-4 col-lg-4 col-xl-4\">\r\n");
      out.write("       <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"...\" alt=\"Card image cap\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">JAVA PROGRAMMING LANGUAGE</h5>\r\n");
      out.write("          <p class=\"card-text\">Some quick example text to build on the card title and make up the bulk of the card's content.</p>\r\n");
      out.write("           <a href=\"#\" class=\"btn userdefinecolor-background text-white\">Read More..</a>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <!-- this is third column -->\r\n");
      out.write("      <div class=\"col-md-4 col-lg-4 col-xl-4\">\r\n");
      out.write("       <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"...\" alt=\"Card image cap\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">JAVA PROGRAMMING LANGUAGE</h5>\r\n");
      out.write("          <p class=\"card-text\">Some quick example text to build on the card title and make up the bulk of the card's content.</p>\r\n");
      out.write("           <a href=\"#\" class=\"btn userdefinecolor-background text-white\">Read More..</a>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("    \r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("     <!-- this is second row -->\r\n");
      out.write("     \r\n");
      out.write("     <div class=\"row mb-4\">\r\n");
      out.write("     <!-- this is first column -->\r\n");
      out.write("      <div class=\"col-md-4 col-lg-4 col-xl-4\">     \r\n");
      out.write("       <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"...\" alt=\"Card image cap\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">JAVA PROGRAMMING LANGUAGE</h5>\r\n");
      out.write("          <p class=\"card-text\">Some quick example text to build on the card title and make up the bulk of the card's content.</p>\r\n");
      out.write("           <a href=\"#\" class=\"btn userdefinecolor-background text-white\">Read More..</a>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <!-- this is second column -->\r\n");
      out.write("      <div class=\"col-md-4 col-lg-4 col-xl-4\">\r\n");
      out.write("       <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"...\" alt=\"Card image cap\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">JAVA PROGRAMMING LANGUAGE</h5>\r\n");
      out.write("          <p class=\"card-text\">Some quick example text to build on the card title and make up the bulk of the card's content.</p>\r\n");
      out.write("           <a href=\"#\" class=\"btn userdefinecolor-background text-white\">Read More..</a>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <!-- this is third column -->\r\n");
      out.write("      <div class=\"col-md-4 col-lg-4 col-xl-4\">\r\n");
      out.write("       <div class=\"card\" style=\"width: 18rem;\">\r\n");
      out.write("          <img class=\"card-img-top\" src=\"...\" alt=\"Card image cap\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("          <h5 class=\"card-title\">JAVA PROGRAMMING LANGUAGE</h5>\r\n");
      out.write("          <p class=\"card-text\">Some quick example text to build on the card title and make up the bulk of the card's content.</p>\r\n");
      out.write("           <a href=\"#\" class=\"btn userdefinecolor-background text-white\">Read More..</a>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("    \r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("       \r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- java script bootstrap libraries -->\r\n");
      out.write("     <script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("     <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/myjs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
